/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import java.io.EOFException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.InetAddress;
import java.net.Socket;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Jacob
 */
public class GameClient extends javax.swing.JFrame {

    /**
     * Creates new form GameClient
     */
    public GameClient() {
        super("Jacob's Game");
        initComponents();
        addPics();
        serverIP = javax.swing.JOptionPane.showInputDialog("What is the host's public IP address?");
        ableToType(false);
        ComponentMover cm = new ComponentMover();
        cm.registerComponent(handCard1, handCard2, handCard3, handCard4, handCard5, handCard6, handCard7, handCard8, handCard9, handCard10, handCard11, handCard12, handCard13, handCard14, handCard15, handCard16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userText = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        chatWindow = new javax.swing.JTextArea();
        GameTabs = new javax.swing.JTabbedPane();
        fieldBG = new javax.swing.JPanel();
        deckPanel = new javax.swing.JPanel();
        fieldLayeredPanel = new javax.swing.JLayeredPane();
        card1Panel = new javax.swing.JPanel();
        card2Panel = new javax.swing.JPanel();
        card3Panel = new javax.swing.JPanel();
        deckPic = new javax.swing.JLabel();
        handBG = new javax.swing.JPanel();
        handLayeredPanel = new javax.swing.JLayeredPane();
        handCard16 = new javax.swing.JPanel();
        handCard15 = new javax.swing.JPanel();
        handCard14 = new javax.swing.JPanel();
        handCard13 = new javax.swing.JPanel();
        handCard12 = new javax.swing.JPanel();
        handCard11 = new javax.swing.JPanel();
        handCard10 = new javax.swing.JPanel();
        handCard9 = new javax.swing.JPanel();
        handCard8 = new javax.swing.JPanel();
        handCard7 = new javax.swing.JPanel();
        handCard6 = new javax.swing.JPanel();
        handCard5 = new javax.swing.JPanel();
        handCard4 = new javax.swing.JPanel();
        handCard3 = new javax.swing.JPanel();
        handCard2 = new javax.swing.JPanel();
        handCard1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        setResizable(false);

        userText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTextActionPerformed(evt);
            }
        });

        sendButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        chatWindow.setEditable(false);
        chatWindow.setColumns(20);
        chatWindow.setRows(5);
        jScrollPane.setViewportView(chatWindow);

        GameTabs.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        fieldBG.setBackground(new java.awt.Color(0, 102, 0));

        javax.swing.GroupLayout deckPanelLayout = new javax.swing.GroupLayout(deckPanel);
        deckPanel.setLayout(deckPanelLayout);
        deckPanelLayout.setHorizontalGroup(
            deckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );
        deckPanelLayout.setVerticalGroup(
            deckPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        card1Panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        card1Panel.setLayout(new javax.swing.OverlayLayout(card1Panel));

        card2Panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        card2Panel.setLayout(new javax.swing.OverlayLayout(card2Panel));

        card3Panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        card3Panel.setLayout(new javax.swing.OverlayLayout(card3Panel));

        javax.swing.GroupLayout fieldLayeredPanelLayout = new javax.swing.GroupLayout(fieldLayeredPanel);
        fieldLayeredPanel.setLayout(fieldLayeredPanelLayout);
        fieldLayeredPanelLayout.setHorizontalGroup(
            fieldLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fieldLayeredPanelLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(card2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
            .addGroup(fieldLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fieldLayeredPanelLayout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(card3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(370, Short.MAX_VALUE)))
            .addGroup(fieldLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fieldLayeredPanelLayout.createSequentialGroup()
                    .addContainerGap(300, Short.MAX_VALUE)
                    .addComponent(card1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(120, Short.MAX_VALUE)))
        );
        fieldLayeredPanelLayout.setVerticalGroup(
            fieldLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fieldLayeredPanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(card2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(fieldLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(fieldLayeredPanelLayout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(card3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(194, Short.MAX_VALUE)))
            .addGroup(fieldLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fieldLayeredPanelLayout.createSequentialGroup()
                    .addContainerGap(147, Short.MAX_VALUE)
                    .addComponent(card1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(64, Short.MAX_VALUE)))
        );
        fieldLayeredPanel.setLayer(card1Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fieldLayeredPanel.setLayer(card2Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fieldLayeredPanel.setLayer(card3Panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout fieldBGLayout = new javax.swing.GroupLayout(fieldBG);
        fieldBG.setLayout(fieldBGLayout);
        fieldBGLayout.setHorizontalGroup(
            fieldBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fieldBGLayout.createSequentialGroup()
                .addComponent(fieldLayeredPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(deckPic, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deckPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        fieldBGLayout.setVerticalGroup(
            fieldBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fieldLayeredPanel)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fieldBGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deckPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(73, 73, 73))
            .addGroup(fieldBGLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(deckPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        GameTabs.addTab("Field of Play", fieldBG);

        handBG.setBackground(new java.awt.Color(0, 102, 0));

        handCard16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        handCard16.setLayout(new javax.swing.OverlayLayout(handCard16));

        handCard15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        handCard15.setLayout(new javax.swing.OverlayLayout(handCard15));

        handCard14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        handCard14.setLayout(new javax.swing.OverlayLayout(handCard14));

        handCard13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        handCard13.setLayout(new javax.swing.OverlayLayout(handCard13));

        handCard12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        handCard12.setLayout(new javax.swing.OverlayLayout(handCard12));

        handCard11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        handCard11.setLayout(new javax.swing.OverlayLayout(handCard11));

        handCard10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        handCard10.setLayout(new javax.swing.OverlayLayout(handCard10));

        handCard9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        handCard9.setLayout(new javax.swing.OverlayLayout(handCard9));

        handCard8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        handCard8.setLayout(new javax.swing.OverlayLayout(handCard8));

        handCard7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        handCard7.setLayout(new javax.swing.OverlayLayout(handCard7));

        handCard6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        handCard6.setLayout(new javax.swing.OverlayLayout(handCard6));

        handCard5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        handCard5.setLayout(new javax.swing.OverlayLayout(handCard5));

        handCard4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        handCard4.setLayout(new javax.swing.OverlayLayout(handCard4));

        handCard3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        handCard3.setLayout(new javax.swing.OverlayLayout(handCard3));

        handCard2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        handCard2.setLayout(new javax.swing.OverlayLayout(handCard2));

        handCard1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        handCard1.setLayout(new javax.swing.OverlayLayout(handCard1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PLACE CARD HERE");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout handLayeredPanelLayout = new javax.swing.GroupLayout(handLayeredPanel);
        handLayeredPanel.setLayout(handLayeredPanelLayout);
        handLayeredPanelLayout.setHorizontalGroup(
            handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(handLayeredPanelLayout.createSequentialGroup()
                .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(handLayeredPanelLayout.createSequentialGroup()
                        .addGap(692, 692, 692)
                        .addComponent(handCard11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(handLayeredPanelLayout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, handLayeredPanelLayout.createSequentialGroup()
                    .addContainerGap(752, Short.MAX_VALUE)
                    .addComponent(handCard12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, handLayeredPanelLayout.createSequentialGroup()
                    .addContainerGap(618, Short.MAX_VALUE)
                    .addComponent(handCard10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(155, 155, 155)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, handLayeredPanelLayout.createSequentialGroup()
                    .addContainerGap(558, Short.MAX_VALUE)
                    .addComponent(handCard9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(215, 215, 215)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, handLayeredPanelLayout.createSequentialGroup()
                    .addContainerGap(484, Short.MAX_VALUE)
                    .addComponent(handCard8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(289, 289, 289)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, handLayeredPanelLayout.createSequentialGroup()
                    .addContainerGap(424, Short.MAX_VALUE)
                    .addComponent(handCard7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(349, 349, 349)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, handLayeredPanelLayout.createSequentialGroup()
                    .addContainerGap(290, Short.MAX_VALUE)
                    .addComponent(handCard5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(483, 483, 483)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(handLayeredPanelLayout.createSequentialGroup()
                    .addGap(156, 156, 156)
                    .addComponent(handCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(617, Short.MAX_VALUE)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(handLayeredPanelLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(handCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(751, Short.MAX_VALUE)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(handLayeredPanelLayout.createSequentialGroup()
                    .addGap(350, 350, 350)
                    .addComponent(handCard6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(423, Short.MAX_VALUE)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(handLayeredPanelLayout.createSequentialGroup()
                    .addGap(215, 215, 215)
                    .addComponent(handCard4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(557, Short.MAX_VALUE)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(handLayeredPanelLayout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(handCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(692, Short.MAX_VALUE)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(handLayeredPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(handCard13, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(763, Short.MAX_VALUE)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(handLayeredPanelLayout.createSequentialGroup()
                    .addGap(144, 144, 144)
                    .addComponent(handCard14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(629, Short.MAX_VALUE)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(handLayeredPanelLayout.createSequentialGroup()
                    .addGap(629, 629, 629)
                    .addComponent(handCard15, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(144, Short.MAX_VALUE)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, handLayeredPanelLayout.createSequentialGroup()
                    .addContainerGap(763, Short.MAX_VALUE)
                    .addComponent(handCard16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        handLayeredPanelLayout.setVerticalGroup(
            handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(handLayeredPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(handCard11, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(handLayeredPanelLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(handCard12, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(283, Short.MAX_VALUE)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(handLayeredPanelLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(handCard10, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(283, Short.MAX_VALUE)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(handLayeredPanelLayout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addComponent(handCard9, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(225, Short.MAX_VALUE)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(handLayeredPanelLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(handCard8, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(282, Short.MAX_VALUE)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(handLayeredPanelLayout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addComponent(handCard7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(225, Short.MAX_VALUE)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(handLayeredPanelLayout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addComponent(handCard5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(225, Short.MAX_VALUE)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(handLayeredPanelLayout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addComponent(handCard3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(226, Short.MAX_VALUE)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(handLayeredPanelLayout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(handCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(226, Short.MAX_VALUE)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(handLayeredPanelLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(handCard6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(282, Short.MAX_VALUE)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(handLayeredPanelLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(handCard4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(282, Short.MAX_VALUE)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(handLayeredPanelLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(handCard2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(282, Short.MAX_VALUE)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(handLayeredPanelLayout.createSequentialGroup()
                    .addGap(296, 296, 296)
                    .addComponent(handCard13, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, handLayeredPanelLayout.createSequentialGroup()
                    .addContainerGap(296, Short.MAX_VALUE)
                    .addComponent(handCard14, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, handLayeredPanelLayout.createSequentialGroup()
                    .addContainerGap(284, Short.MAX_VALUE)
                    .addComponent(handCard15, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)))
            .addGroup(handLayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, handLayeredPanelLayout.createSequentialGroup()
                    .addContainerGap(284, Short.MAX_VALUE)
                    .addComponent(handCard16, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)))
        );
        handLayeredPanel.setLayer(handCard16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        handLayeredPanel.setLayer(handCard15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        handLayeredPanel.setLayer(handCard14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        handLayeredPanel.setLayer(handCard13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        handLayeredPanel.setLayer(handCard12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        handLayeredPanel.setLayer(handCard11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        handLayeredPanel.setLayer(handCard10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        handLayeredPanel.setLayer(handCard9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        handLayeredPanel.setLayer(handCard8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        handLayeredPanel.setLayer(handCard7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        handLayeredPanel.setLayer(handCard6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        handLayeredPanel.setLayer(handCard5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        handLayeredPanel.setLayer(handCard4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        handLayeredPanel.setLayer(handCard3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        handLayeredPanel.setLayer(handCard2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        handLayeredPanel.setLayer(handCard1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        handLayeredPanel.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout handBGLayout = new javax.swing.GroupLayout(handBG);
        handBG.setLayout(handBGLayout);
        handBGLayout.setHorizontalGroup(
            handBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(handLayeredPanel)
        );
        handBGLayout.setVerticalGroup(
            handBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(handLayeredPanel)
        );

        GameTabs.addTab("My Hand", handBG);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(GameTabs))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GameTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextActionPerformed
        // TODO add your handling code here:
        sendMessage(evt.getActionCommand());
        userText.setText("");
    }//GEN-LAST:event_userTextActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
        sendMessage(userText.getText());
        userText.setText("");
    }//GEN-LAST:event_sendButtonActionPerformed

    //determines if the user is able to type
 private void ableToType(final boolean ability) {
   SwingUtilities.invokeLater(() -> {
       userText.setEditable(ability);
       sendButton.setEnabled(ability);
   });
 }
    
 //updates chatWindow
 private void showMessage(final String message) {
   SwingUtilities.invokeLater(() -> {
       chatWindow.append(message);
   });
 }   
    
 //send a message to the client
 private void sendMessage(String message) {
   try {
     output.writeObject("CLIENT - " + message);
     output.flush();
     showMessage("\nCLIENT - " + message);
   } catch(IOException ioError) {
     chatWindow.append("\n ERROR: USER COULD NOT SEND MESSAGE");
   }
 }
 
//closes connections and streams after done chatting
private void closeItems() {
    showMessage("\n Closing connections... \n");
    ableToType(false);
    try {
      output.close();
      input.close();
      connection.close();
    }  catch(IOException ioError) {
    }
}
    
 //during the chat conversation
 private void whileChatting() throws IOException {
   String message = " You are now connected! \n";
   sendMessage(message);
   //receive();
   ableToType(true);
   do {
     try {
       //place where only strings are allowed
       message = (String) input.readObject();
       showMessage("\n" + message);
     } catch(ClassNotFoundException cnfError) {
       showMessage("\n USER DID NOT SEND A VALID MESSAGE! \n");
     }
   } while(!message.equals("SERVER - END"));
 }
 
 //get stream to send and recieve data
 private void setupStreams() throws IOException {
   output = new ObjectOutputStream(connection.getOutputStream());
   output.flush();
   input = new ObjectInputStream(connection.getInputStream());
   showMessage(" Streams are now setup! \n");
 }
 
 //connect to a server
 private void connectToServer() throws IOException {
   showMessage("Attempting connection with IP address " + serverIP + "...\n");
   connection = new Socket(InetAddress.getByName(serverIP), 35697);
   showMessage("Connected to: " + connection.getInetAddress().getHostName() + "\n");
 }
    
 //connect to the server
 public void startRunning() {
   try {
     connectToServer();
     setupStreams();
     whileChatting();
   } catch(EOFException eofError) {
     showMessage("\n Client terminated the connection.");
   } catch(IOException ioError) {
   } finally {
     closeItems();
   }
 }
 
private void addPics() {
    deckPic = new JLabel(new ImageIcon("Images/deck.png"));
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        GameClient client = new GameClient();
        client.setVisible(true);
        client.startRunning();      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane GameTabs;
    private javax.swing.JPanel card1Panel;
    private javax.swing.JPanel card2Panel;
    private javax.swing.JPanel card3Panel;
    private javax.swing.JTextArea chatWindow;
    private javax.swing.JPanel deckPanel;
    private javax.swing.JLabel deckPic;
    private javax.swing.JPanel fieldBG;
    private javax.swing.JLayeredPane fieldLayeredPanel;
    private javax.swing.JPanel handBG;
    private javax.swing.JPanel handCard1;
    private javax.swing.JPanel handCard10;
    private javax.swing.JPanel handCard11;
    private javax.swing.JPanel handCard12;
    private javax.swing.JPanel handCard13;
    private javax.swing.JPanel handCard14;
    private javax.swing.JPanel handCard15;
    private javax.swing.JPanel handCard16;
    private javax.swing.JPanel handCard2;
    private javax.swing.JPanel handCard3;
    private javax.swing.JPanel handCard4;
    private javax.swing.JPanel handCard5;
    private javax.swing.JPanel handCard6;
    private javax.swing.JPanel handCard7;
    private javax.swing.JPanel handCard8;
    private javax.swing.JPanel handCard9;
    private javax.swing.JLayeredPane handLayeredPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables
    private ObjectOutputStream output;
    private ObjectInputStream input;
    private String serverIP;
    private Socket connection;
}
